### ISSUE TITLE
PCAP only

### ISSUE THREAD

**Issue by mgaulton** [blacktop/docker-bro#1]
is there a reason this appears to be intended to work with pcap files only rather than live capture?

**Comment by blacktop** [comment]
When I first made this docker-image, docker's security was questionable.  So I didn't think it was safe to connect it to the actually interface and do live capture.  However, I intend on adding a bro user and adding that functionality soon with a docker-entrypoint.sh file.  Thanks for your interest!

**Comment by mgaulton** [comment]
That would be awesome. I found a decent snort docker, now I just have to set up an ELK instance and get the logs into it lol Thanks again.

**Comment by blacktop** [comment]
I am sooooo sorry this took me so long, but I have been very focused on my malice project and my day job :(

Does this help or did you need something more? https://github.com/blacktop/docker-bro#capture-live-traffic
