### ISSUE TITLE
Remove Volume Instruction in Dockerfiles

### ISSUE THREAD

**Issue by Zalgo2462** [blacktop/docker-bro#10]
Each of the Dockerfiles have the line:

```VOLUME ["/pcap"]```

However, the README instructs users to use a bind mount to insert pcap files into the container. Additionally, the docker-compose files use bind mounts as well.

VOLUME instructions carry a lot of baggage and tend to get in the way when they aren't needed. 

For further reading on the VOLUME statement and why it gets in the way, see
https://boxboat.com/2017/01/23/volumes-and-dockerfiles-dont-mix/

Is there a reason for the VOLUME statement that I am missing?

**Comment by blacktop** [comment]
There is no real reason other than when I started out with docker waaaaaaaay back in 2014 that's how I learned to build Dockerfiles ;)
