### ISSUE TITLE
Bro Kafka integration Error

### ISSUE THREAD

**Issue by parmenides** [blacktop/docker-bro#11]
Hi

I tried to run bro with kafka integration but it comes up with the following error
$docker run --rm -v /home/cyborg/brov:/pcap blacktop/bro:kafka -P -r heartbleed.pcap local "Site::local_nets += { 192.168.11.0/24 }"
fatal error in /usr/local/share/bro/site/local.bro, line 105: can't find Bro/Kafka/logs-to-kafka.bro

**Comment by blacktop** [comment]
this will take a while to build in docker cloud, please re-open if this doesn't fix it for you and thank you for letting me know! 👍
