### ISSUE TITLE
Unable to access el2 repo

### ISSUE THREAD

**Issue by Keithsc** [blacktop/docker-bro#13]
Hi, I think there might be a problem with the instructions for your bro image with elasticsearch as I can't get el2 the image el2 loaded.....

 docker -l debug run -it --rm -v `pwd`:/pcap --link elasticsearch el2 -r heartbleed.pcap local "Site::local_nets += { 192.168.11.0/24 }"
Unable to find image 'el2:latest' locally
/run/torcx/bin/docker: Error response from daemon: pull access denied for el2, repository does not exist or may require 'docker login'.
See '/run/torcx/bin/docker run --help'.

I tried creating an account at docker.com and using "docker login" but I still get repo errors.

can you help ?

also.... the docker elasticsearch example you provide loads in the hearbleed.pcap file, could you tell me how to alter it to use an interface ethX instead as the input ?

Thanks
Keith.

**Comment by petorian** [comment]
I get the same issue.

**Comment by blacktop** [comment]
It was a dumb typo.  Thank you for pointing this out to me! 👍
