### ISSUE TITLE
error with kafka plugin

### ISSUE THREAD

**Issue by wei294597950** [blacktop/docker-bro#17]
i got error when i run as follow:
"root@localhost:/home/xuwei/bro_workpalce/test4# docker run --rm \
          -v `pwd`:/pcap \
          --link kafka:localhost \
          blacktop/bro:kafka -P -r heartbleed.pcap local "Site::local_nets += { 192.168.11.0/24 }"
Unable to find image 'blacktop/bro:kafka' locally
kafka: Pulling from blacktop/bro
5d20c808ce19: Pulling fs layer 
477dbbea3083: Pulling fs layer 
af8fbe84de2b: Pulling fs layer 
5e9fb904e5fb: Waiting 
c7d677aba90d: Waiting 
b156ec96e1bf: Waiting 
docker: error pulling image configuration: received unexpected HTTP status: 500 Internal Server Error."

how to solve this

**Comment by jamshid** [comment]
Hi @wei294597950 just curious if you found a fix for that `docker pull` error, please share if you did. https://github.com/docker/distribution-library-image/issues/89 claims`-e REGISTRY_VALIDATION_DISABLED=true` fixes it but it does not for me.
