### ISSUE TITLE
Bro configs

### ISSUE THREAD

**Issue by goaquin** [blacktop/docker-bro#3]
Hello,
I have two questions:
-First: I want to set the log format into JSON, but when I create the volume with the json-logs.bro file like this
`./bro/json/:/opt/bro/scripts/policy/tuning/`
It creates that file, but the logs are not in JSON format. It is possible to set that?
[https://www.bro.org/sphinx/scripts/policy/tuning/json-logs.bro.html](url)

-Second: Where are the bro config files? broccoli.conf, broctl.cfg, networks.cfg and node.cfg. I want to import my configuration from a working Bro.

Regards,
Joaquín Silva

**Comment by blacktop** [comment]
You can see the paths here: https://github.com/blacktop/docker-bro/blob/master/2.5/Dockerfile#L53

and notice that I overwrite the local.bro here: https://github.com/blacktop/docker-bro/blob/master/2.5/Dockerfile#L58

So maybe if you placed your bro-script here: `/usr/local/share/bro/policy/tuning/` instead or pointed to it in the local.bro

**Comment by goaquin** [comment]
I solved it adding this line:
`RUN sed -i 's/use_json = F/use_json = T/g' /usr/local/share/bro/base/frameworks/logging/writers/ascii.bro`

**Comment by blacktop** [comment]
👍
