### ISSUE TITLE
"Getting Started" instructions: github site instead file downloaded

### ISSUE THREAD

**Issue by techge** [blacktop/docker-bro#5]
On https://hub.docker.com/r/blacktop/bro/ in the Getting Started section the second command reads
`wget https://github.com/blacktop/docker-bro/blob/master/scripts/local.bro`
which does download the github site and not the local.bro. You probably want something like
`wget https://raw.githubusercontent.com/blacktop/docker-bro/master/scripts/local.bro`

**Comment by blacktop** [comment]
@techge thank you for this! 👍
