### ISSUE TITLE
permitions deny

### ISSUE THREAD

**Issue by RomanSilinenko** [blacktop/docker-bro#9]
Hi, could you please help to fix the issues with file permitions? 
if i run as root the offered command:
`#docker run --rm -it --cap-add=NET_RAW  --net=host -v `pwd`:/pcap:rw blacktop/bro -i ens160`
if have the following:
```
[root@cbtlinux bro]# docker logs bro
listening on ens160
error: packet_filter/Log::WRITER_ASCII: cannot open packet_filter.log: Permission denied
error: packet_filter/Log::WRITER_ASCII: terminating thread
error: reporter/Log::WRITER_ASCII: cannot open reporter.log: Permission denied
error: reporter/Log::WRITER_ASCII: terminating thread
1512745949.920468 error: weird/Log::WRITER_ASCII: cannot open weird.log: Permission denied
1512745949.920468 error: weird/Log::WRITER_ASCII: terminating thread
1512745950.385030 error: dns/Log::WRITER_ASCII: cannot open dns.log: Permission denied
1512745950.385030 error: dns/Log::WRITER_ASCII: terminating thread
1512745950.408958 error: files/Log::WRITER_ASCII: cannot open files.log: Permission denied
1512745950.408958 error: files/Log::WRITER_ASCII: terminating thread
1512745950.408958 error: http/Log::WRITER_ASCII: cannot open http.log: Permission denied
1512745950.408958 error: http/Log::WRITER_ASCII: terminating thread
1512745950.555018 error: x509/Log::WRITER_ASCII: cannot open x509.log: Permission denied
1512745950.555018 error: x509/Log::WRITER_ASCII: terminating thread
1512745950.623345 error: tunnel/Log::WRITER_ASCII: cannot open tunnel.log: Permission denied
1512745950.623345 error: tunnel/Log::WRITER_ASCII: terminating thread

...
and so on. 
```
what is the problem?

moreover i did "chmod a+rw" for the host directory which binds to /pcap

**Comment by RomanSilinenko** [comment]
i've figured out there's something with /pcap folder inside of the container. although is has 777 permission, any attempt to read it causes permission deny error. how it is possible?

**Comment by blacktop** [comment]
I believe you run as `root` inside the container, but it is not really root so maybe it doesn't have the ability to read the pcap folder when it is mounted? oh yeah I can see you are running as `root` outside the container so I think that is why.  

If you tried again not as root (on your host) I think it might start working?

**Comment by RomanSilinenko** [comment]
Hi! Not sure i got the idea why root is not quite root, but anyway, I've created a user, added him into docker group and ran the container again. doesn't help much. 
`[roman@cbtlinux ~]$ docker run -d --cap-add=NET_RAW --name bro --net=host -v `pwd`:/pcap:rw blacktop/bro -i ens160 -C
60ca2382bd76ec6ffac60008c194b32b2f3c3a8918e56f35336bd52301beb366
[roman@cbtlinux ~]$ docker logs bro
listening on ens160
1512993328.085274 error: packet_filter/Log::WRITER_ASCII: cannot open packet_filter.log: Permission denied
1512993328.085274 error: packet_filter/Log::WRITER_ASCII: terminating thread
1512993328.085575 error: reporter/Log::WRITE`

**Comment by megastef** [comment]
@RomanSilinenko  you try `--pid=host` or `--cap-add=NET_ADMIN` or `--privileged`?

**Comment by RomanSilinenko** [comment]
thanks @megastef, `--privileged` has helped. i see log files now in docker host folder.
